// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileManager() {
  return window['go']['main']['App']['FileManager']();
}

export function WriteEnv(arg1) {
  return window['go']['main']['App']['WriteEnv'](arg1);
}
