// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSearchFolder():Promise<string>;

export function MakeConfig():Promise<void>;

export function OpenFolder():Promise<string>;

export function SelectFolder():Promise<string>;

export function WriteURLAndUpdate():Promise<void>;
