// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolder(arg1) {
  return window['go']['main']['App']['GetFolder'](arg1);
}

export function MakeConfig() {
  return window['go']['main']['App']['MakeConfig']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function WriteJsonFile(arg1, arg2) {
  return window['go']['main']['App']['WriteJsonFile'](arg1, arg2);
}

export function WriteURLAndUpdate() {
  return window['go']['main']['App']['WriteURLAndUpdate']();
}
