// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolder(arg1:string):Promise<string>;

export function MakeConfig():Promise<void>;

export function OpenFolder():Promise<string>;

export function SelectFolder(arg1:string):Promise<any>;

export function WriteJsonFile(arg1:string,arg2:any):Promise<any>;

export function WriteURLAndUpdate():Promise<void>;
